export const LAYOUT_SET_VIEWPORT = 'LAYOUT_SET_VIEWPORT'
export const LAYOUT_SET_CONTENT = 'LAYOUT_SET_CONTENT'
export const LAYOUT_SET_SCROLL_POSITION = 'LAYOUT_SET_SCROLL_POSITION'

export const PROGRESS_ADD_IMAGE = 'PROGRESS_ADD_IMAGE'
